# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "James Vecore"
description: > # this means to ignore newlines until "email:"
   James Vecore's Blog

email: james.vecore@gmail.com
#blog logo
logo: "/assets/images/jv_logo.jpg"
# blog cover
cover: "/assets/images/default.jpg"

name: 'James Vecore'
author: 'James Vecore'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.jamesvecore.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/jamesvecore
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: vimeo-square
    url:  https://vimeo.com/jamesvecore
    desc: Watch me on Vimeo
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://www.linkedin.com/in/jamesvecore
    desc: Stalk me on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon: twitter
    url:  https://twitter.com/jamesvecore
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: rss
    url:  "/feed.xml"
    desc: Subscribe to me RSS
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
